.TH "script_options" 3 "Version pulgamecanica (arosado-)" "ft_script" \" -*- nroff -*-
.ad l
.nh
.SH NAME
script_options \- Configuration options for the script command\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ft_script\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBoutput_file\fP"
.br
.ti -1c
.RI "const char * \fBcommand\fP"
.br
.ti -1c
.RI "int \fBappend_mode\fP"
.br
.ti -1c
.RI "int \fBquiet_mode\fP"
.br
.ti -1c
.RI "int \fBreturn_exit_status\fP"
.br
.ti -1c
.RI "int \fBflush_mode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configuration options for the script command\&. 

This structure holds all command-line options and their state\&. It encapsulates configuration to make it easy to pass around and test\&.
.PP
Ownership: Created on stack in main(), passed by pointer to functions Lifetime: Exists for entire program execution 
.SH "Field Documentation"
.PP 
.SS "int script_options::append_mode"
Append mode flag (-a option)
.IP "\(bu" 2
0: truncate existing file (default)
.IP "\(bu" 2
1: append to existing file 
.PP

.SS "const char* script_options::command"
Command to execute (for -c option)
.IP "\(bu" 2
NULL: run interactive shell
.IP "\(bu" 2
Non-NULL: execute this command Ownership: Points to argv string, do NOT free 
.PP

.SS "int script_options::flush_mode"
Flush output after each write (-f option)
.IP "\(bu" 2
0: use buffered output (default)
.IP "\(bu" 2
1: flush after each write
.PP
.PP
Note: This is a BONUS feature\&. When enabled, fflush() is called after each write to the output file, ensuring real-time updates\&. This is useful for monitoring scripts in progress but has a performance impact\&. 
.SS "const char* script_options::output_file"
Output file path
.IP "\(bu" 2
NULL: use DEFAULT_TYPESCRIPT
.IP "\(bu" 2
Non-NULL: caller-provided filename Ownership: Points to argv string, do NOT free 
.PP

.SS "int script_options::quiet_mode"
Quiet mode flag (-q option)
.IP "\(bu" 2
0: print start/done messages (default)
.IP "\(bu" 2
1: suppress messages 
.PP

.SS "int script_options::return_exit_status"
Return child exit status (-e option)
.IP "\(bu" 2
0: always exit with 0 (default)
.IP "\(bu" 2
1: exit with child's exit status 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ft_script from the source code\&.
.SH SEE ALSO
.BR ft_script.h (3),
.BR script_state (3)
